In [1]:
import pandas as pd
import random

In [2]:
### Sampling: taking 100000 lines from train.txt
trainfile = 'train.txt'

n = 2847802
s = 500000
skip = sorted(random.sample(xrange(n),n-s))

train = pd.read_csv(trainfile, header = None, sep = '\t', skiprows = skip)

train.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0,6,0,20130606000104450,1,VhLrOxuUPqd63CL,windows_chrome,113.200.249.*,333,334,...,2811067692,250,250,2,0,5,7097e4210dea4d69f07f0f5e4343529c,361e128affece850342293213691a043,3386,"10006,10057,14273"
1,0,6,0,20130606000104479,1,VhTO1e57PvkyXWE,windows_chrome,124.91.42.*,94,100,...,mm_10027070_118039_10308280,160,600,2,1,0,47905feeb59223468fb898b3c9ac024d,361e128affece850342293213691a043,3386,"13866,10006,10063,10111"
2,0,6,0,20130606000104992,1,VhkSO71iPlM6FVc,windows_chrome,175.1.175.*,201,204,...,3923448949,300,250,1,0,5,44966cc8da1ed40c95d59e863c8c75f0,361e128affece850342293213691a043,3386,"10063,13866,10006,13800,10093,10111"
3,0,6,0,20130606000105660,1,Vhd2Lrz8LQFP3bC,windows_ie,110.208.6.*,216,217,...,4017603800,336,280,2,0,5,ff5123fb9333ca095034c62fdaaf51aa,361e128affece850342293213691a043,3386,"10075,10052,10057,10076,14273,10006,10111"
4,0,6,0,20130606000105664,1,Vhkr1nT2OqTLlgC,windows_chrome,124.119.231.*,374,376,...,3190262199,728,90,2,0,5,b90c12ed2bd7950c6027bf9c6937c48a,361e128affece850342293213691a043,3386,13866

In [6]:
### Write sampled lines to txt file
train.to_csv('train_sample.txt', sep = '\t', header = None, index = None)